services:
  postgres_container:
    ports:
      - 5500:5432
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=shopapp
      - POSTGRES_USER=thang
      - POSTGRES_PASSWORD=123456
    volumes:
      - D:\postgres_data:/var/lib/postgresql/data
    restart: always
  backend:
    build:
      dockerfile: Dockerfile
    container_name: shopapp_container
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container:5432/shopapp
      - SPRING_DATASOURCE_USERNAME=thang
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres_container
    restart: always